;; Wrappers and utilities matrix multiplicaiton, etc.
;; based on generateme/fastmath.
(ns utils.fastmats
  (:require [clojure.math :as math]
            [fastmath.vector :as fvec]
            [fastmath.matrix :as fmat]
            [fastmath.core :as fm]
            [utils.math :as um]))

(def transpose fmat/transpose) ; alias

;; generateme/fastmath supports a variety of different vector and
;; matrix representations, but they don't all have the same conveniences
;; and don't necessarily work with the multiplication operators.
;; These are aliases for the current best choice for me.  See
;; https://clojurians.zulipchat.com/#narrow/channel/151924-data-science/topic/Matrix-vector.20multiplication.20in.20fastmath/near/569973078
(def mkvec double-array)
(def mkmat fm/seq->double-double-array)

;; At present need to convert eye to Java Array2D for mult with Array2D
(defn eye 
  "Returns identity matrix of dimension d x d in Java Array2D format."
  [d]
  (fmat/mat->array2d (fmat/eye d)))

;; Fewer multiplications. Faster for larger m and n than simpler version.
;; Uses mutual recursion, but stack depth is O(log2 n).
(defn mpow
  "Multiplies a square matrix by itself n times.  n must be a nonnegative
  integer or positive floating-point number with no fractional part. Returns
  the identity nmatrix of the same shape when n=0."
  [m n]
  (let [[h w] (fmat/shape m)]
    (cond 
      (not= h w) 
      (print (str "mpow only multiplies square matrices. Matrix shape was [" h " " w "].")) ; throw?

      (or (< n 0) (not (zero? (rem n 1))))
      (print (str "mpow only accepts nonnegative integer powers. Exponent was " n)) ; throw?

      (zero? n) (eye h)

      :else 
      (letfn [(either-pow [acc-mat k]
                (cond (= k 1) acc-mat
                      (even? k) (even-pow acc-mat k)
                      :else (fmat/mulm m (even-pow acc-mat (dec k)))))
              (even-pow [acc-mat k]
                (let [factor (either-pow acc-mat (/ k 2))]
                  (fmat/mulm factor factor)))]
        (either-pow m (long n)))))) ; allow float integers

(defn mat-powers
  "Returns a lazy sequence of powers of a square matrix beginning with m^0,
  i.e. begining with the identity matrix of the same size.  Specific
  elements can be extracted e.g. using take-nth, keep-indexed, or
  utils/misc/elems-at. (Uses iterate, so that each matrix is generated by
  multiplying by the previous one.)"
  [m]
  (iterate (partial fmat/mulm m)
             (eye (first (fmat/shape m)))))

(defn choose-mat-powers-sequentially
  "Returns a lazy sequence of transition matrices that are integer powers
  of square matrix m for each exponent in collection expts (which should be
  finite, but may be in any order). Exponents must be nonnegative integers,
  which may be in a float representation. (Uses mat-powers, so all
  intermediate matrices are generated along the way. Use
  choose-mat-powers-sequentially for closely spaced exponents; use
  choose-mat-powers-separately or choose-mat-powers-parallel for widely
  spaced exponents.)"
  [m expts]
  (let [expts-set (set (map long expts))
        n (count expts-set)] ; don't count dupes
    (take n (keep-indexed (fn [i m] (when (expts-set i) m))
                          (mat-powers m)))))

(defn choose-mat-powers-separately
  "Returns a lazy sequence of transition matrices that are integer powers
  of square matrix m for each exponent in collection expts (which should be
  finite, but may be in any order). Exponents must be nonnegative integers,
  which may be in a float representation. If present, mapper should be a
  function like map or pmap, which can map a function across a sequence.
  (Generates each matrix power from scratch using mpow, so each element of
  the returned sequence is O(log m), but higher powers don't take advantage
  of what was done to calculate lower powers. Use
  choose-mat-powers-sequentially for closely spaced exponents; use
  choose-mat-powers-separately or choose-mat-powers-parallel for widely
  spaced exponents.)"
  ([m expts] (choose-mat-powers-separately map m expts))
  ([mapper m expts] (mapper (partial mpow m) (map long expts))))

(defn choose-mat-powers-parallel
  "Like choose-mat-powers-separately, but uses pmap rather than map.
  See choose-mat-powers-separately for more info."
  [m expts] 
  (choose-mat-powers-separately pmap m expts))

;; Strategizing:
;; 
;; (a) If difference between this exponent e2 and the previous one e1 
;; is small, then just multiply the e1 by m a few times to get e2.
;; (b) If difference is larger, then use mpow.
;; How large of a difference?
;; One rule would be to use mpow iff e1 is <= sqrt e2.
;; But suppose e2 = 10M = 1000^2, and e1 is 1001. Isn't there
;; a better way than multiplying m^1001 by m 998999 times, or better
;; starting mpow from scratch on that exponent.
;; OK, what about this algorithm:
;; If e1 = sqrt e2, then calc e2 as m^e1 * m^e1.
;; If e1 < sqrt e2, then iterate on sqrt e2 to generate newmat, with e1 
;;   as the previous exponent, and then after generating sqrt e2, calc e2 
;;   as newmat * newmat.
;; If e1 > sqrt e2, then iterate on (- e2 e1), and multiply the result
;; by m^e1.
;; 
;; Or what if I maintain a cache of previous mpow results that
;; are useful for higher powers?
(defn choose-mat-powers-artfully
  "Returns a lazy sequence of transition matrices that are integer powers
  of square matrix m for each exponent in collection expts, which must be
  monotonically increasing [AND FINITE??]. Exponents must be nonnegative
  integers, which may be in a float representation."
  [mapper m expts]
  ;; check for empty expts?
  (let [[h w] (fmat/shape m)] ; check for equality??
    (loop [prevm (eye h)
           es expts]
    (let [this-e (first es)
          prev-e (second es) ; try to get rid of unnecess indexing later
          sqe (math/floor (fm/sqrt this-e))]
      (cond (== prev-e sqe) "FIXME"
            )
  ))))

(defn mat-squares
  [m]
  (iterate (fn [mat] (fmat/mulm mat mat)) m))

;; Trying to figure out a way to use mat-squares or similar to create a
;; more efficient sequential-ish generation of powers.
(defn mat-experimental
  [m expts]
  (let [indexed-squares (map-indexed vector (mat-squares m))]
    2)) ; what here?


(defn make-prob-states
  "Given a sequence of transition NxM matrices and an initial state vector
  of length M, generates a sequence containing the vectors that result from
  multiplying each matrix (on the left) with the vector (on the right)."
  [tran-mats init-state]
  (mapv (fn [m] (fmat/mulv m init-state))
        tran-mats))

;; TODO only works with real eigenvalues
(defn test-eigen-vecs-vals
  "Test the eigenvector/eigenvalue relationship is correct. Returns a sequence
  of Clojure booleans."
  [m]
  (let [decomp (fmat/eigen-decomposition m {:backend :colt})
        evecs (fmat/decomposition-component decomp :eigenvectors)
        revals (fmat/decomposition-component decomp :real-eigenvalues)
        ievals (fmat/decomposition-component decomp :imag-eigenvalues)]
    (map #(fvec/delta-eq (fmat/mulv m %1) ; matrix-vector mult
                         (fvec/mult %1 %2)) ; vector-scalar mult
         evecs
         (vec revals))))

(comment
  (def m (fm/seq->double-double-array [[1 2 3][4 5 6][7 8 9]]))
  (def ms (mat-powers m))
  (def mx (mat-experimental m))
  (take 10 ms)
  (nth ms 9)
  (nth ms 10)
  (def mpsep (choose-mat-powers-separately m [0 1 4 9]))
  (def mpsep2 (choose-mat-powers-separately m [0.0 1.0 4.0 9.0]))
  (def mpseq (choose-mat-powers-sequentially m [0 1 4 9]))
  (def mpseq2 (choose-mat-powers-sequentially m [1.0 4.0 9])) ; loops forever why?

  (def m2s (mat-squares m))
  (take 4 m2s)
  (def mpsep (choose-mat-powers-separately m [1 2 4 16]))
)


(comment
  (def m (fm/seq->double-double-array [[1 2 3][4 5 6][7 8 9]]))
  (mpow m 10)
  (mpow-slow m 10)
  (= (mpow m 10) (mpow-slow m 10))
  (mpow m 0)
  (mpow m 0.0)
  (mpow m -2)
  (mpow m 2.5)
  (mpow m 2.0) ; should succeed
  (def m1 (fm/seq->double-double-array [[1 2 3][4 5 6]]))
  (mpow m1 2)

  (mpow m 4)
  (mpow m 5)
  (make-mat-powers m [1 4 5])
  (def ms (mat-powers m))
  (take 8 m)

  (def m (fm/seq->double-double-array [[1 2 3][4 5 6][7 8 9]]))
  (def I (fmat/eye 3))
  (fmat/mulm I m)
  ; eval (effective-root-form): (fmat/mulm I m)
  ; (err) Execution error (ClassCastException) at fastmath.matrix.Mat3x3/mulm (matrix.clj:313).
  ; (err) class [[D cannot be cast to class fastmath.matrix.Mat3x3 ([[D is in module java.base of loader 'bootstrap'; fastmath.matrix.Mat3x3 is in unnamed module of loader clojure.lang.DynamicClassLoader @c1e1f4c)
  (def Ireal (fmat/eye 3 true))
  (fmat/mulm Ireal m)
  ; eval (effective-root-form): (fmat/mulm Ireal m)
  ; (err) Execution error (ClassCastException) at fastmath.matrix/eval41805$fn (matrix.clj:686).
  ; (err) class [[D cannot be cast to class org.apache.commons.math3.linear.RealMatrix ([[D is in module java.base of loader 'bootstrap'; org.apache.commons.math3.linear.RealMatrix is in unnamed module of loader 'app')
  ;; THIS WORKS:
  (def Idouble (fm/seq->double-double-array [[1 0 0][0 1 0][0 0 1]]))
  (fmat/mulm Idouble m)

  (fmat/diagonal 1 1 1)

  (type I)
  (type Ireal)
  (type Idouble)
)


(comment
;; There's a bug here that causes an infinite loop though the second
;; clause of the second if.  I don't understand it, but another verison
;; using `keep-indexed` works, so I'm not going to bother to fix this
;; unless there's a good reason to resuscitate it.
(defn make-mat-powers-sequentially-bad
  [m expts]
  (let [powseq (mat-powers m)]
    (loop [i 0, pows (mat-powers m), es expts, acc-pows []]
      (if (empty? expts)
        acc-pows
        (if (= i (first es))
          (recur (inc i)
                 (rest es)
                 (rest pows)
                (conj acc-pows (first pows)))
          (recur (inc i)
                 es ; don't move on until we find one
                 (rest pows)
                 acc-pows))))))
)

(comment
  ;; Simple, tail recursive, but slow for moderately large m and n.
  (defn mpow-slow
    "Multiplies a square matrix by itself n times.  n must be a positive
    integer or positive floating-point number with no fractional part."
    [m n]
    (let [[h w] (fmat/shape m)]
      (cond 
        (not= h w)
        (print (str "mpow only multiplies square matrices; shape is [" h " " w "].")) ; throw?

        (or (<= n 0) (not (== (rem n 1) 0)))
        (print "mpow only accepts positive integer powers.") ; throw?

        :else 
        (loop [i 1, acc-mat m]
          (if (= i n)
            acc-mat
            (recur (inc i)
                   (fmat/mulm m acc-mat)))))))
)

